services:

  frontend:
    image: medilabo-frontend
    build:
      context: frontend
    ports:
      - "80:80"
    depends_on:
      - gateway


  demographics:
    image: medilabo-demographics
    build:
      context: demographics
    container_name: demographics
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/patientdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin


  db:
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  patienthistory:
    image: medilabo-patienthistory
    build:
      context: patienthistory
    container_name: patienthistory
    ports:
      - "8082:8082"
    depends_on:
      - mongodb


  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db


  assessment:
    image: medilabo-assessment
    build:
      context: assessment
    container_name: assessment
    ports:
      - "8083:8083"
    depends_on:
      - demographics
      - patienthistory
    environment:
      SPRING_PROFILES_ACTIVE: docker


  gateway:
    image: medilabo-gateway
    build:
      context: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - demographics
      - patienthistory
      - assessment
    environment:
      SPRING_PROFILES_ACTIVE: docker


volumes:
  postgres-data:
  mongodb-data: