spring:
     application:
          name: DemographicsApplication
     datasource:
         url: jdbc:postgresql://postgres:5432/patientdb
         username: postgres
         password: admin
     jpa:
       hibernate:
         ddl-auto: update
       properties:
         hibernate:
           default_schema: public
       show-sql: true


server:
  port : 8081

logging:
  level:
    org.springframework.security: TRACE